### ISSUE TITLE
PR to the official Joplin repository

### ISSUE THREAD

**Issue by alexanderadam** [hrqmonteiro/joplin-theme#1]
Hello Henrique,

I think your theme looks _really_ great. :pray: 
Would you consider making [a PR to the official repo](https://github.com/laurent22/joplin/tree/dev/packages/lib/themes)?

This would make this theme easier accessible for everyone (which especially makes sense on mobile devices, [since you can't even use custom style sheets on them](https://github.com/laurent22/joplin/issues/3677)).

Apart from that everyone would automatically get updates in case the theme even improves.

**Comment by hrqmonteiro** [comment]
> Hello Henrique,
> 
> I think your theme looks _really_ great. pray
> Would you consider making [a PR to the official repo](https://github.com/laurent22/joplin/tree/dev/packages/lib/themes)?
> 
> This would make this theme easier accessible for everyone (which especially makes sense on mobile devices, [since you can't even use custom style sheets on them](https://github.com/laurent22/joplin/issues/3677)).
> 
> Apart from that everyone would automatically get updates in case the theme even improves.

Hello, and thanks for the compliments! I appreciate.

I indeed have considered making a PR, but i have to adapt the theme to the new appearance of Joplin, which i already did, like, 50%, and i have polished the colors a little bit to it looks better now. I have this and a second theme i was using. I should upload them to this repo soon, so maybe keep in touch here. Then i will consider making a PR.

Thanks for the consideration, again!

**Comment by alexanderadam** [comment]
> I indeed have considered making a PR

That's great!

> Thanks for the consideration, again!

Just to clarify: I'm not part of the Joplin team in case it appeared like that. I'm just a user who was happy stumbling about your awesome theme.

**Comment by alexanderadam** [comment]
Oh @hrqmonteiro, does this mean that you won't open a PR to the official repository? :disappointed:
